# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/java-mvn"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    target-branch: "main"
  - package-ecosystem: "maven"
    directory: "/java-stream-mvn"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    target-branch: "main"
  - package-ecosystem: "maven"
    directory: "/spring-amqp"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    target-branch: "main"
  - package-ecosystem: "maven"
    directory: "/spring-amqp-stream"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    target-branch: "main"
  - package-ecosystem: "gradle"
    directory: "/java-gradle"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    target-branch: "main"

