[package]
name = "rabbitmq-tutorials"
version = "1.0.0"
authors = ["Michal Malek <michalm@fastmail.fm>"]
edition = "2018"

[dependencies]
futures = "0.3.21"
lapin = "2.1.1"
tokio = { version = "1.20.3", features = ["full"] }
uuid = { version = "1.1.1", features = ["v4"] }
tokio-stream = "0.1"
