services:
  php:
    build:
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app:cached
    command: sh -c 'trap "exit 0" TERM; tail -f /dev/null & wait'

  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    restart: always
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
